-- =====================================================================
-- Paradise City Rooms — database setup
--
-- Run this whole file once in Supabase → SQL Editor → "New query" → Run.
--
-- Rules enforced here (the website shows the same rules, but the
-- database is the final judge, so nobody can bypass them):
--   * Only @paradisecity.be addresses can create an account.
--   * quinten@paradisecity.be automatically becomes admin.
--   * Bookings: 15-minute steps, between 07:00 and 20:00 (Brussels time),
--     not in the past, at most 3 months ahead, never overlapping.
-- =====================================================================

create extension if not exists btree_gist with schema extensions;

-- ---------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text not null unique,
  full_name text not null check (char_length(full_name) between 1 and 100),
  role text not null default 'member' check (role in ('member', 'admin')),
  blocked boolean not null default false,
  theme jsonb,
  created_at timestamptz not null default now()
);

create table public.rooms (
  id smallint generated by default as identity primary key,
  name text not null check (char_length(btrim(name)) between 1 and 60),
  capacity integer not null check (capacity between 1 and 500),
  color text not null default '#6366f1' check (color ~ '^#[0-9a-fA-F]{6}$'),
  sort_order integer not null default 0
);

insert into public.rooms (id, name, capacity, color, sort_order) values
  (1, 'Room 1 (MKT side)', 6, '#8b5cf6', 1),
  (2, 'Room 2 (Middle)', 10, '#10b981', 2),
  (3, 'Room 3 (big screen)', 8, '#f59e0b', 3);

select setval(pg_get_serial_sequence('public.rooms', 'id'), 3);

create table public.bookings (
  id uuid primary key default gen_random_uuid(),
  room_id smallint not null references public.rooms (id) on delete cascade,
  user_id uuid not null default auth.uid(),
  title text not null,
  guests text[] not null default '{}',
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  series_id uuid,
  recurrence jsonb,
  cancelled_at timestamptz,
  cancelled_by uuid,
  cancel_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint bookings_user_id_fkey foreign key (user_id)
    references public.profiles (id) on delete cascade,
  constraint bookings_cancelled_by_fkey foreign key (cancelled_by)
    references public.profiles (id) on delete set null,
  constraint bookings_time_order check (ends_at > starts_at),
  -- The heart of the system: two active bookings of the same room can never overlap.
  constraint bookings_no_overlap exclude using gist (
    room_id with =,
    tstzrange(starts_at, ends_at, '[)') with &&
  ) where (cancelled_at is null)
);

create index bookings_starts_at_idx on public.bookings (starts_at);
create index bookings_user_id_idx on public.bookings (user_id);
create index bookings_series_id_idx on public.bookings (series_id) where series_id is not null;

-- ---------------------------------------------------------------------
-- Helper functions used by the security rules
-- ---------------------------------------------------------------------

create or replace function public.is_active_member()
returns boolean
language sql stable security definer set search_path = ''
as $$
  select exists (
    select 1 from public.profiles where id = auth.uid() and not blocked
  );
$$;

create or replace function public.is_admin()
returns boolean
language sql stable security definer set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin' and not blocked
  );
$$;

-- ---------------------------------------------------------------------
-- New accounts: only @paradisecity.be, and create the profile row
-- ---------------------------------------------------------------------

create or replace function public.handle_new_user()
returns trigger
language plpgsql security definer set search_path = ''
as $$
declare
  allowed_domain constant text := 'paradisecity.be';
  admin_email constant text := 'quinten@paradisecity.be';
  v_email text := lower(new.email);
begin
  if split_part(v_email, '@', 2) <> allowed_domain then
    raise exception 'Only @% email addresses can create an account.', allowed_domain;
  end if;

  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    v_email,
    left(coalesce(nullif(btrim(new.raw_user_meta_data ->> 'full_name'), ''), split_part(v_email, '@', 1)), 100),
    case when v_email = admin_email then 'admin' else 'member' end
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------
-- Booking rules (checked on every insert/update)
-- ---------------------------------------------------------------------

create or replace function public.bookings_before_write()
returns trigger
language plpgsql set search_path = ''
as $$
declare
  tz constant text := 'Europe/Brussels';
  day_start constant time := '07:00';
  day_end constant time := '20:00';
  months_ahead constant interval := interval '3 months';
  local_start timestamp;
  local_end timestamp;
  times_changed boolean;
  clean_guests text[];
begin
  if tg_op = 'UPDATE' then
    -- These never change after creation.
    new.id := old.id;
    new.user_id := old.user_id;
    new.created_at := old.created_at;
    new.series_id := old.series_id;
    new.recurrence := old.recurrence;

    if old.cancelled_at is not null then
      raise exception 'This booking has been cancelled and can no longer be changed.';
    end if;

    if new.cancelled_at is not null then
      -- Cancelling: record who and when, keep everything else as it was.
      new.cancelled_at := now();
      new.cancelled_by := coalesce(auth.uid(), new.cancelled_by);
      new.cancel_reason := left(nullif(btrim(new.cancel_reason), ''), 300);
      new.room_id := old.room_id;
      new.title := old.title;
      new.guests := old.guests;
      new.starts_at := old.starts_at;
      new.ends_at := old.ends_at;
      new.updated_at := now();
      return new;
    end if;

    new.cancelled_by := null;
    new.cancel_reason := null;
    times_changed := new.starts_at is distinct from old.starts_at
      or new.ends_at is distinct from old.ends_at
      or new.room_id is distinct from old.room_id;
  else
    new.user_id := coalesce(new.user_id, auth.uid());
    new.cancelled_at := null;
    new.cancelled_by := null;
    new.cancel_reason := null;
    new.created_at := now();
    times_changed := true;
  end if;

  new.updated_at := now();

  new.title := btrim(coalesce(new.title, ''));
  if char_length(new.title) = 0 then
    raise exception 'Please enter a topic for the meeting.';
  end if;
  if char_length(new.title) > 120 then
    raise exception 'The topic can be at most 120 characters.';
  end if;

  select coalesce(array_agg(distinct g), '{}') into clean_guests
  from (select lower(btrim(x)) as g from unnest(coalesce(new.guests, '{}')) as x) s
  where g <> '';
  if cardinality(clean_guests) > 30 then
    raise exception 'You can add at most 30 guests.';
  end if;
  if exists (select 1 from unnest(clean_guests) g where g !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$') then
    raise exception 'One of the guest email addresses is not valid.';
  end if;
  new.guests := clean_guests;

  if times_changed then
    local_start := new.starts_at at time zone tz;
    local_end := new.ends_at at time zone tz;

    if extract(epoch from new.starts_at)::bigint % 900 <> 0
       or extract(epoch from new.ends_at)::bigint % 900 <> 0 then
      raise exception 'Bookings must start and end on a quarter of an hour.';
    end if;

    if local_start::date <> local_end::date
       or local_start::time < day_start
       or local_end::time > day_end then
      raise exception 'Rooms can be booked between 07:00 and 20:00.';
    end if;

    if new.ends_at <= now()
       or ((tg_op = 'INSERT' or new.starts_at is distinct from old.starts_at)
           and new.starts_at < now() - interval '15 minutes') then
      raise exception 'You can''t book a room in the past.';
    end if;

    if local_start::date > ((now() at time zone tz)::date + months_ahead)::date then
      raise exception 'Rooms can be booked at most 3 months ahead.';
    end if;
  end if;

  return new;
end;
$$;

create trigger bookings_before_write
  before insert or update on public.bookings
  for each row execute function public.bookings_before_write();

-- ---------------------------------------------------------------------
-- Security (row level security + column privileges)
-- ---------------------------------------------------------------------

alter table public.profiles enable row level security;
alter table public.rooms enable row level security;
alter table public.bookings enable row level security;

revoke all on public.profiles from anon, authenticated;
revoke all on public.rooms from anon, authenticated;
revoke all on public.bookings from anon, authenticated;

-- Profiles: colleagues can see each other (name + email are shown on bookings).
-- Everyone can change only their own name and colour theme.
grant select on public.profiles to authenticated;
grant update (full_name, theme) on public.profiles to authenticated;

create policy "Members can see colleagues" on public.profiles
  for select to authenticated
  using (id = auth.uid() or public.is_active_member());

create policy "Users can update their own profile" on public.profiles
  for update to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

-- Rooms: everyone can see them, only the admin can rename them / change capacity.
grant select on public.rooms to authenticated;
grant update (name, capacity, color) on public.rooms to authenticated;

create policy "Members can see rooms" on public.rooms
  for select to authenticated
  using (public.is_active_member());

create policy "Admins can update rooms" on public.rooms
  for update to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- Bookings: everyone sees everything; you change your own, the admin changes all.
-- Bookings are never hard-deleted by users; cancelling sets cancelled_at.
grant select, insert on public.bookings to authenticated;
grant update (room_id, title, guests, starts_at, ends_at, cancelled_at, cancel_reason)
  on public.bookings to authenticated;

create policy "Members can see bookings" on public.bookings
  for select to authenticated
  using (public.is_active_member());

create policy "Members can book for themselves" on public.bookings
  for insert to authenticated
  with check (public.is_active_member() and user_id = auth.uid());

create policy "Owners and admins can change bookings" on public.bookings
  for update to authenticated
  using (public.is_active_member() and (user_id = auth.uid() or public.is_admin()))
  with check (public.is_active_member() and (user_id = auth.uid() or public.is_admin()));

-- ---------------------------------------------------------------------
-- Create one booking or a recurring series in one go.
--   p_slots: [{ "starts_at": "...", "ends_at": "..." }, ...]
--   Dates that are already taken are skipped, unless the admin
--   chooses to overrule them (then the existing bookings are cancelled).
-- ---------------------------------------------------------------------

create or replace function public.create_bookings(
  p_room_id smallint,
  p_title text,
  p_guests text[],
  p_slots jsonb,
  p_recurrence jsonb default null,
  p_override boolean default false
)
returns jsonb
language plpgsql security invoker set search_path = ''
as $$
declare
  v_slot jsonb;
  v_start timestamptz;
  v_end timestamptz;
  v_series uuid;
  v_id uuid;
  v_conflicts uuid[];
  v_created uuid[] := '{}';
  v_overridden uuid[] := '{}';
  v_skipped jsonb := '[]';
begin
  if not public.is_active_member() then
    raise exception 'Your account is not allowed to book rooms.';
  end if;
  if p_override and not public.is_admin() then
    raise exception 'Only the admin can overrule other bookings.';
  end if;
  if jsonb_typeof(p_slots) <> 'array' or jsonb_array_length(p_slots) = 0 then
    raise exception 'Nothing to book.';
  end if;
  if jsonb_array_length(p_slots) > 200 then
    raise exception 'A series can have at most 200 dates.';
  end if;

  if jsonb_array_length(p_slots) > 1 then
    v_series := gen_random_uuid();
  end if;

  for v_slot in select value from jsonb_array_elements(p_slots) loop
    v_start := (v_slot ->> 'starts_at')::timestamptz;
    v_end := (v_slot ->> 'ends_at')::timestamptz;

    select coalesce(array_agg(b.id), '{}') into v_conflicts
    from public.bookings b
    where b.room_id = p_room_id
      and b.cancelled_at is null
      and tstzrange(b.starts_at, b.ends_at, '[)') && tstzrange(v_start, v_end, '[)');

    if cardinality(v_conflicts) > 0 then
      if not p_override then
        v_skipped := v_skipped || jsonb_build_array(jsonb_build_object('starts_at', v_start, 'ends_at', v_end));
        continue;
      end if;
      update public.bookings
      set cancelled_at = now(),
          cancel_reason = 'Overruled by the admin for "' || btrim(p_title) || '"'
      where id = any (v_conflicts);
      v_overridden := v_overridden || v_conflicts;
    end if;

    insert into public.bookings (room_id, title, guests, starts_at, ends_at, series_id, recurrence)
    values (p_room_id, p_title, coalesce(p_guests, '{}'), v_start, v_end, v_series,
            case when v_series is not null then p_recurrence end)
    returning id into v_id;
    v_created := v_created || v_id;
  end loop;

  return jsonb_build_object(
    'created', to_jsonb(v_created),
    'skipped', v_skipped,
    'overridden', to_jsonb(v_overridden)
  );
end;
$$;

-- ---------------------------------------------------------------------
-- Change this and all following bookings of a recurring series.
-- ---------------------------------------------------------------------

create or replace function public.update_series(
  p_booking_id uuid,
  p_room_id smallint,
  p_title text,
  p_guests text[],
  p_start time,
  p_end time
)
returns uuid[]
language plpgsql security invoker set search_path = ''
as $$
declare
  tz constant text := 'Europe/Brussels';
  v_booking public.bookings;
  v_taken text;
  v_ids uuid[];
begin
  select * into v_booking from public.bookings where id = p_booking_id and cancelled_at is null;
  if not found or v_booking.series_id is null then
    raise exception 'This recurring booking could not be found.';
  end if;

  -- Give a friendly list of dates that clash with someone else's booking.
  select string_agg(to_char(s.starts_at at time zone tz, 'Dy DD Mon'), ', ' order by s.starts_at)
  into v_taken
  from public.bookings s
  where s.series_id = v_booking.series_id
    and s.cancelled_at is null
    and s.starts_at >= v_booking.starts_at
    and exists (
      select 1 from public.bookings o
      where o.room_id = p_room_id
        and o.cancelled_at is null
        and (o.series_id is distinct from v_booking.series_id)
        and tstzrange(o.starts_at, o.ends_at, '[)') && tstzrange(
          ((s.starts_at at time zone tz)::date + p_start) at time zone tz,
          ((s.starts_at at time zone tz)::date + p_end) at time zone tz,
          '[)')
    );
  if v_taken is not null then
    raise exception 'The room is already booked on: %', v_taken;
  end if;

  with changed as (
    update public.bookings b
    set room_id = p_room_id,
        title = p_title,
        guests = coalesce(p_guests, '{}'),
        starts_at = ((b.starts_at at time zone tz)::date + p_start) at time zone tz,
        ends_at = ((b.starts_at at time zone tz)::date + p_end) at time zone tz
    where b.series_id = v_booking.series_id
      and b.cancelled_at is null
      and b.starts_at >= v_booking.starts_at
    returning b.id
  )
  select coalesce(array_agg(id), '{}') into v_ids from changed;

  return v_ids;
end;
$$;

revoke execute on function public.create_bookings(smallint, text, text[], jsonb, jsonb, boolean) from public, anon;
revoke execute on function public.update_series(uuid, smallint, text, text[], time, time) from public, anon;
grant execute on function public.create_bookings(smallint, text, text[], jsonb, jsonb, boolean) to authenticated;
grant execute on function public.update_series(uuid, smallint, text, text[], time, time) to authenticated;

-- ---------------------------------------------------------------------
-- Live updates: the calendar refreshes automatically when someone books.
-- ---------------------------------------------------------------------

alter publication supabase_realtime add table public.bookings;
